const industry = [
  '',
  'Aerospace, defence & security',
  'Asset & wealth management',
  'Automotive',
  'Banking & capital markets',
  'Capital projects & infrastructure',
  'Chemicals',
  'Communications',
  'Energy, utilities & mining',
  'Engineering & construction',
  'Entertainment & media',
  'Financial services',
  'Forest, paper & packaging',
  'Government & public services',
  'Healthcare',
  'Hospitality & leisure',
  'Industrial manufacturing',
  'Insurance',
  'Metals',
  'Pharmaceuticals & life sciences',
  'Private equity',
  'Retail & consumer',
  'Sovereign investment funds',
  'Technology',
  'Transportation & logistics',
  'Other'
]

export default industry;